name: PersonalSpawnPoint
main: me.excuze.setrespawn.Main
version: 1.1
author: Excuze#3063
api-version: 1.16

commands:
  psp:
    description: Run /psp help for a list of commands!
    aliases: [personalspawnpoint]
